const asset = (path) => `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

const shared = {
  kicker: "An evening invitation",
  date: "날짜는 함께 정해요",
  dateEn: "We’ll pick a night",
  endTitleKo: "나중에 봐요",
};

export const routes = [
  {
    id: "yangggochi-highball",
    titleKo: "양꼬치 & 하이볼",
    titleEn: "Yang-kkochi & highball",
    areaKo: "길동",
    areaEn: "Gangdong",
    walkLabel: "약 670m · 9분 산책",
    walkBlurbKo: "양꼬치를 먹고, 길동에서 하이볼 한잔으로 이어갑니다.",
    walkBlurbEn: "Nine minutes through Gildong",
    routeUrl: asset("route.geojson"),
    overview: { center: [127.13842, 37.53742], zoom: 16.1, pitch: 0, bearing: -12 },
    start: {
      step: "01",
      stepEn: "Yang-kkochi",
      name: "이가네양꼬치 길동점",
      nameEn: "Igane Yang-kkochi Gildong",
      category: "양꼬치",
      address: "서울 강동구 진황도로 94 101, 102호",
      lng: 127.1367356,
      lat: 37.5359442,
      naver: "https://naver.me/FG3vkcLC",
      blurbKo: "길동에서 양꼬치로 저녁을 시작합니다.",
      blurbEn: "Lamb skewers to start the night.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20250906_68/1757148524757ajzH3_JPEG/1000014946.jpg",
        alt: "이가네양꼬치 길동점",
      },
      highlights: ["양등심꼬치", "양왕꼬치", "양갈비", "가지요리", "토마토계란볶음"],
    },
    end: {
      step: "02",
      stepEn: "Highball",
      name: "창",
      nameEn: "Chang",
      category: "이자카야 · 하이볼",
      address: "서울 강동구 양재대로 1491 1층",
      lng: 127.140097,
      lat: 37.5389023,
      naver: "https://naver.me/xSBU5hHf",
      blurbKo: "걸어서 이자카야에서 하이볼로 마무리합니다.",
      blurbEn: "A highball around the corner.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20241130_19/1732966603290WR5eL_JPEG/1000003441.jpg",
        alt: "창",
      },
      highlights: ["하이볼", "과일하이볼", "오꼬노미야끼", "참치타다끼", "나가사키짬뽕나베"],
    },
  },
  {
    id: "naengmyeon-pork",
    titleKo: "냉면 & 돼지고기",
    titleEn: "Naengmyeon & pork",
    areaKo: "천호동",
    areaEn: "Gangdong",
    walkLabel: "약 30m · 1분 산책",
    walkBlurbKo: "냉면을 먹고, 골목 건너 돼지고기로 이어갑니다.",
    walkBlurbEn: "Just around the corner",
    routeUrl: asset("route-naengmyeon.geojson"),
    overview: { center: [127.1296, 37.54253], zoom: 18.1, pitch: 0, bearing: -12 },
    start: {
      step: "01",
      stepEn: "Naengmyeon",
      name: "송월냉면",
      nameEn: "Songwol Naengmyeon",
      category: "냉면",
      address: "서울 강동구 천중로18길 57 1층",
      lng: 127.1295853,
      lat: 37.5423803,
      naver: "https://naver.me/FK5vf06T",
      blurbKo: "천호 냉면골목의 노포. 사골 육수 한 그릇으로 시작합니다.",
      blurbEn: "A Cheonho naengmyeon house. Start with a cold bowl.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20210214_27/1613294401889nW0SW_JPEG/uuUWazNTQEb8Cfi2WiGs4xdq.jpeg.jpg",
        alt: "송월냉면",
      },
      highlights: ["물냉면", "비빔냉면", "열무물냉면", "열무비빔냉면", "고기만두"],
    },
    end: {
      step: "02",
      stepEn: "Pork",
      name: "깡돈 천호점",
      nameEn: "Kkdons Cheonho",
      category: "돼지고기구이",
      address: "서울 강동구 구천면로33길 24 1층",
      lng: 127.1296221,
      lat: 37.5426721,
      naver: "https://naver.me/FV7YsX9f",
      blurbKo: "바로 옆에서 돼지 특수부위로 저녁을 이어갑니다.",
      blurbEn: "Pork cuts, just around the corner.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20230322_20/1679450749847LMR63_JPEG/KakaoTalk_20230307_161228976_20.jpg",
        alt: "깡돈 천호점",
      },
      highlights: ["뒷고기", "덜미살", "뽈살", "항정살", "돼지껍데기"],
    },
  },
  {
    id: "pizza-coffee",
    titleKo: "피자 & 커피",
    titleEn: "Pizza & coffee",
    areaKo: "길동 · 성내동",
    areaEn: "Gangdong",
    walkLabel: "약 880m · 11분 산책",
    walkBlurbKo: "피자를 먹고, 성안로를 따라 커피까지 걷습니다.",
    walkBlurbEn: "Eleven quiet minutes",
    routeUrl: asset("route-pizza.geojson"),
    overview: { center: [127.13249, 37.53116], zoom: 15.6, pitch: 0, bearing: -18 },
    start: {
      step: "01",
      stepEn: "Pizza",
      name: "델리치오자",
      nameEn: "Deliciosa",
      category: "피자",
      address: "서울 강동구 천호대로 1106",
      lng: 127.1343111,
      lat: 37.5348662,
      naver: "https://naver.me/xEx30ECY",
      blurbKo: "화덕 피자로 저녁을 시작합니다.",
      blurbEn: "Dinner starts with wood-fired pizza.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20240924_210/1727163444992PHw7y_JPEG/DSC02990-2.jpg",
        alt: "델리치오자",
      },
      highlights: ["마르게리따", "디아볼라", "꽈뜨로포르마지", "트러플 풍기", "아페롤 스프리츠"],
    },
    end: {
      step: "02",
      stepEn: "Coffee",
      name: "채스우드커피",
      nameEn: "Chesswood Coffee",
      category: "카페 · 디저트",
      address: "서울 강동구 성안로 42 1층",
      lng: 127.1306702,
      lat: 37.5274517,
      naver: "https://naver.me/xllBDs0V",
      blurbKo: "성안로를 걸어 호주 스타일 로스터리에서 마무리합니다.",
      blurbEn: "We walk down Seongnae, then finish with coffee.",
      photo: { src: asset("photos/chesswood-1.jpg"), alt: "채스우드커피" },
      highlights: ["오지 카푸치노", "플랫화이트", "테라스", "우드 인테리어"],
    },
  },
];

export { shared };
