const shared = {
  kicker: "An evening invitation",
  date: "날짜는 함께 정해요",
  dateEn: "We’ll pick a night",
  endTitleKo: "나중에 봐요",
};

export const routes = [
  {
    id: "dinner-coffee",
    titleKo: "저녁 & 커피",
    titleEn: "Dinner & coffee",
    areaKo: "성내동",
    areaEn: "Gangdong",
    walkLabel: "약 380m · 5분 산책",
    walkBlurbKo: "저녁을 먹고, 성내동 골목으로 커피까지 걷습니다.",
    walkBlurbEn: "Five quiet minutes",
    routeUrl: "/route.geojson",
    overview: { center: [127.13188, 37.52655], zoom: 16.2, pitch: 0, bearing: -18 },
    start: {
      step: "01",
      stepEn: "Dinner",
      name: "상록분식",
      nameEn: "Sangnok Bunsik",
      category: "분식 · 백반",
      address: "서울 강동구 양재대로87길 35",
      lng: 127.1331061,
      lat: 37.5257786,
      naver: "https://naver.me/5gFgYdWQ",
      blurbKo: "성내동 골목의 노포. 찌개 한 그릇으로 저녁을 시작합니다.",
      blurbEn: "A neighborhood kitchen. Dinner starts here.",
      highlights: ["청국장", "들깨순두부", "오징어볶음", "라볶이", "뚝배기 불고기"],
    },
    end: {
      step: "02",
      stepEn: "Coffee",
      name: "채스우드커피",
      nameEn: "Chesswood Coffee",
      category: "카페 · 디저트",
      address: "서울 강동구 성안로 42 1층",
      lng: 127.1306702,
      lat: 37.5274517,
      naver: "https://naver.me/FFGMoP5l",
      blurbKo: "호주 스타일 로스터리에서 저녁을 마무리합니다.",
      blurbEn: "We walk five minutes, then finish the night with coffee.",
      photo: { src: "/photos/chesswood-1.jpg", alt: "채스우드커피" },
      highlights: ["오지 카푸치노", "플랫화이트", "테라스", "우드 인테리어"],
    },
  },
  {
    id: "naengmyeon-pork",
    titleKo: "냉면 & 돼지고기",
    titleEn: "Naengmyeon & pork",
    areaKo: "천호동",
    areaEn: "Gangdong",
    walkLabel: "약 30m · 1분 산책",
    walkBlurbKo: "냉면을 먹고, 골목 건너 돼지고기로 이어갑니다.",
    walkBlurbEn: "Just around the corner",
    routeUrl: "/route-naengmyeon.geojson",
    overview: { center: [127.1296, 37.54253], zoom: 18.1, pitch: 0, bearing: -12 },
    start: {
      step: "01",
      stepEn: "Naengmyeon",
      name: "송월냉면",
      nameEn: "Songwol Naengmyeon",
      category: "냉면",
      address: "서울 강동구 천중로18길 57 1층",
      lng: 127.1295853,
      lat: 37.5423803,
      naver: "https://naver.me/FK5vf06T",
      blurbKo: "천호 냉면골목의 노포. 사골 육수 한 그릇으로 시작합니다.",
      blurbEn: "A Cheonho naengmyeon house. Start with a cold bowl.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20210214_27/1613294401889nW0SW_JPEG/uuUWazNTQEb8Cfi2WiGs4xdq.jpeg.jpg",
        alt: "송월냉면",
      },
      highlights: ["물냉면", "비빔냉면", "열무물냉면", "열무비빔냉면", "고기만두"],
    },
    end: {
      step: "02",
      stepEn: "Pork",
      name: "깡돈 천호점",
      nameEn: "Kkdons Cheonho",
      category: "돼지고기구이",
      address: "서울 강동구 구천면로33길 24 1층",
      lng: 127.1296221,
      lat: 37.5426721,
      naver: "https://naver.me/FV7YsX9f",
      blurbKo: "바로 옆에서 돼지 특수부위로 저녁을 이어갑니다.",
      blurbEn: "Pork cuts, just around the corner.",
      photo: {
        src: "https://ldb-phinf.pstatic.net/20230322_20/1679450749847LMR63_JPEG/KakaoTalk_20230307_161228976_20.jpg",
        alt: "깡돈 천호점",
      },
      highlights: ["뒷고기", "덜미살", "뽈살", "항정살", "돼지껍데기"],
    },
  },
];

export { shared };
